### ISSUE TITLE
Add an anonymous mode

### ISSUE THREAD

**Issue by Euregan** [Euregan/aperoweb#6]
Add a mode anonymizing the data to allow publication of screenshots

**Comment by zyhou** [comment]
Can't understand the problem and the solution :/ Can you explain more?

**Comment by zyhou** [comment]
Some inspiration site:

- https://meetup.letsreact.io/
- https://www.caen.camp/
- https://www.paris-web.fr/
- https://www.dotjs.io/
- http://nodejs.paris/meetups

**Comment by Euregan** [comment]
Actually, terrible idea :D
